[package]
name = "rust_kafka_lambda"
version = "1.0.112"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemafy = "0.6.0"
schemafy_core = { version = "0.6.0" }
serde = "1.0.193"
serde_json = "1.0.108"
serde_derive = "1.0.152"
chrono = "0.4.31"
aws-config = "0.57.2"
aws-sdk-dynamodb = "1.6.0"
lambda_runtime = "0.8.3"
aws_lambda_events = "0.12.1"
tokio = { version = "1.35.0", features = ["full"] }
rdkafka = { version = "0.36.0", features = ["ssl", "gssapi-vendored"] }
async-trait = "0.1.74"
strum_macros = "0.25.3"
futures = "0.3.29"
log = "0.4.20"
slog = "2.7.0"
slog-json = "2.6.1"
slog-term = "2.9.0"
slog-async = "2.8.0"
slog-stdlog = "4.1.1"
slog-scope = "4.4.0"
slog-envlogger = "2.2.0"
lib-base64 = "2.0.4"

[dev-dependencies]
testcontainers = "0.15.0"
http = "1.0.0"
