[package]
name = "rust_kafka_lambda"
version = "1.0.16"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemafy = "0.6.0"
schemafy_core = { version = "0.6.0" }
serde = "1.0.160"
serde_json = "1.0.95"
serde_derive = "1.0.152"
chrono = "0.4.24"
aws-config = "0.54.1"
aws-sdk-dynamodb = "0.24.0"
lambda_runtime = "0.7.3"
aws_lambda_events = { git = "https://github.com/kayhannay/aws-lambda-events" }
tokio = { version = "1.27.0", features = ["full"] }
rdkafka = { version = "0.29.0", features = ["ssl", "gssapi-vendored"] }
async-trait = "0.1.68"
strum_macros = "0.24.3"
futures = "0.3.28"
log = "0.4.17"
slog = "2.7.0"
slog-json = "2.6.1"
slog-term = "2.9.0"
slog-async = "2.7.0"
slog-stdlog = "4.1.1"
slog-scope = "4.4.0"
slog-envlogger = "2.2.0"
lib-base64 = "2.0.3"

[dev-dependencies]
testcontainers = "0.14.0"
http = "0.2.9"
