name: build-release

on:
  push:
    branches:
      - "main"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu"
      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-cache
      - name: Install Cargo lambda and cross
        run: |
          cargo install cross
          pip install cargo-lambda
      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
            @semantic-release-cargo/semantic-release-cargo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
